export { Hono } from 'https://deno.land/x/hono@v4.0.8/mod.ts';
export { html } from 'https://deno.land/x/hono@v4.0.8/helper/html/index.ts';
export { StudentClient } from 'https://deno.land/x/classcharts_api@v2.10.0/mod.ts';
export { ICalCalendarMethod } from 'npm:ical-generator@6.0.1';
import ical from "npm:ical-generator@6.0.1";
export { ical };
import dayjs from 'npm:dayjs@1.11.10';
export { dayjs };
export { encodeHex } from "https://deno.land/std@0.218.2/encoding/hex.ts";
export { outdent } from "https://deno.land/x/outdent@v0.8.0/mod.ts";
import figlet from 'https://deno.land/x/deno_figlet@1.0.0/mod.ts';
export { figlet };